### ISSUE TITLE
Improve the footer design

### ISSUE THREAD

**Issue by Amandeep4567** [Amandeep4567/bank_modern_app#5]
We are looking to enhance the footer design of the HooBank website to make it more visually appealing, functional, and user-friendly. The current footer has a basic structure, but we want to improve its layout, style, and content to align better with our modern brand image.

Here are the key areas for improvement:

Visual Hierarchy: Add more distinct separation between sections (Useful Links, Community, Partner, etc.) to make it easier for users to scan.
Color and Typography: Use colors and typography that match the overall brand identity while ensuring good readability. Consider making important links (like Terms & Services) stand out more.
Icons: The social media icons at the bottom should be more prominent or visually balanced with the rest of the footer content.
Spacing: Increase the spacing between sections and links to reduce clutter and enhance readability.
Responsive Design: Ensure the footer adapts well to different screen sizes, especially mobile devices.
Additional Elements: You may suggest including a subscription field for newsletters, a small logo in the footer, or other elements that can enhance the footer’s functionality and aesthetics.
Please refer to the attached image for the current footer design. The new design should be clean, intuitive, and cohesive with the overall website theme.

**Comment by khushi505** [comment]
Assign me

**Comment by Amandeep4567** [comment]
yeah go for it
